const QUESTIONS = {
  komfort: [
    "Aká bola tvoja obľúbená hračka alebo predmet v detstve a prečo?",
    "Keby si mohol/mohla mať akékoľvek zvieratko ako domáceho miláčika (aj mýtické), čo by to bolo?",
    "Na aký najvtipnejší spoločný zážitok si spomínaš?",
    "Keby si mal/a popísať svoj dnešný deň ako filmový žáner, aký by to bol?",
    "Aká je tvoja najobľúbenejšia vôňa a akú spomienku ti evokuje?",
    "Keby sme mali zajtra vyraziť na spontánny výlet, kam by si chcel/a ísť?",
    "Ktorá pesnička ťa zaručene roztancuje alebo ti zlepší náladu?",
    "Keby si mohol/mohla ovládať jednu superschopnosť, čo by to bolo?",
    "Aké jedlo ti najviac pripomína detstvo a domov?",
    "Ktorá kniha, film alebo seriál ťa v poslednom čase najviac zaujal a prečo?",
    "Čo ťa dnes v práci alebo počas dňa úprimne rozosmialo?",
    "Aký najbizarnejší talent máš, o ktorom veľa ľudí nevie?",
    "Keby si mal/a zjesť jedno jedlo po zvyšok svojho života, čo by to bolo?",
    "Ktoré ročné obdobie máš najradšej a aká aktivita k nemu pre teba neodmysliteľne patrí?",
    "Keby sme mali večer len pre seba bez technológií, čo by sme robili?",
    "Aká bola tvoja prvá kazeta, CD alebo pesnička, ktorú si si kúpil/a alebo obľúbil/a?",
    "Ktorú krajinu na svete by si chcel/a navštíviť len kvôli jej jedlu?",
    "Čo je tvoj najväčší 'guilty pleasure' (skrytá neresť/potešenie)?",
    "Aká bola tvoja najobľúbenejšia rozprávka, keď si bol/a malý/á?",
    "Keby si mohol/mohla stráviť 24 hodín v koži niekoho iného, kto by to bol?",
    "Keby si mal/a možnosť vrátiť sa v čase a dať svojmu 18-ročnému ja jednu radu, čo by to bolo?",
    "Aké najťažšie alebo najvtipnejšie jedlo si kedy v živote ochutnal/a a ako to chutilo?",
    "Ktorý film alebo seriál by si dokázal/a pozerať stále dokola a nikdy ťa neomrzí?",
    "Ak by si mohol/mohla okamžite začať hovoriť akýmkoľvek cudzím jazykom, ktorý by to bol?",
    "Čo je tvoj najväčší zlozvyk, o ktorom vieš, ale nedokážeš ho (alebo nechceš) zmeniť?",
    "Aká je tvoja najstaršia spomienka z detstva, ktorú si stále jasne pamätáš?",
    "Keby si si mal/a vybrať jednu pieseň, ktorá bude hrať zakaždým, keď vstúpiš do miestnosti, čo by to bolo?",
    "Aká bola tvoja najobľúbenejšia školská aktivita alebo predmet a prečo?",
    "Ak by si mohol/mohla stráviť večer s akoukoľvek historickou osobnosťou, kto by to bol?",
    "Čo ťa zaručene dokáže upokojiť po naozaj stresujúcom dni?",
    "Ktorá domáca práca je tvoja najmenej obľúbená a ktorú naopak robíš celkom rád/rada?",
    "Ak by si vyhral/a v lotérii 10 000 eur, čo je prvá vec, ktorú by si si kúpil/a (len pre radosť)?",
    "Máš nejakú obľúbenú spomienku na to, ako sme spolu trávili čas v prírode?",
    "Ktorý zmysel (zrak, sluch, čuch, hmat, chuť) považuješ za svoj najsilnejší?",
    "Aký najlepší darček si v živote dostal/a a od koho to bolo?",
    "Ak by si mohol/mohla prežiť jeden deň ako postava z videohry alebo knihy, kto by to bol?",
    "Ktorá kaviareň, reštaurácia alebo miesto v našom meste má pre teba najlepšiu atmosféru?",
    "Čo je tá najdivnejšia vec, ktorej sa iracionálne bojíš?",
    "Keby si mal/a napísať zoznam troch vecí, ktoré ťa dnes urobili šťastným/šťastnou, čo by tam bolo?",
    "Akú najzábavnejšiu SMS správu si odo mňa kedy dostal/a alebo si na ňu pamätáš?",
    "Ktorý šport alebo fyzickú aktivitu by si chcel/a v živote vyskúšať, ale doteraz si na to nemal/a odvahu?",
    "Aká je tvoja najobľúbenejšia spoločenská hra a kedy sme ju naposledy hrali?",
    "Keby si mohol/mohla zmeniť jednu vec na našom byte/dome bez ohľadu na peniaze, čo by to bolo?",
    "Aká bola tvoja najobľúbenejšia kniha v detstve a koľkokrát si ju čítal/a?",
    "Keby sme mali zajtra vyraziť na piknik, aké tri dobroty by si určite zabalil/a?",
    "Čo je pre teba najlepšia definícia 'pohodového víkendu'?",
    "Ak by si mal/a možnosť stráviť deň s nejakým slávnym športovcom alebo umelcom, kto by to bol?",
    "Aká je tvoja najobľúbenejšia sladkosť alebo dezert, ktorému nikdy neodoláš?",
    "Máš radšej prekvapenia, alebo máš rád/rada veci vopred naplánované?",
    "Ktorá spoločná fotka nás dvoch je tvoja najobľúbenejšia a prečo?"
  ],
  rozvoj: [
    "Čo pre teba znamená naša láska a ako cítiš, že ťa osobnostne rozvíja?",
    "Čo je momentálne tvoja najväčšia osobná výzva, s ktorou vnútorne zápasíš?",
    "Ktorá tvoja vlastnosť ti v živote najviac pomáha a ktorá ti naopak najviac prekáža?",
    "Aké najdôležitejšie životné poučenie si si odniesol/odniesla z nejakého minulého neúspechu?",
    "Čo robíš, keď cítiš, že si pod veľkým stresom? Ako ti vtedy môžem najlepšie pomôcť?",
    "Ktorá udalosť v tvojom živote najviac formovala to, kým si dnes?",
    "Aké správanie alebo reakciu u seba by si chcel/a v budúcnosti zlepšiť?",
    "Čo pre teba znamená pojem 'úspešný život' a ako sa táto predstava časom zmenila?",
    "Kedy sa cítiš najviac nepochopený/á a čo by ti pomohlo cítiť sa lepšie?",
    "Aké hodnoty sú pre teba v živote najdôležitejšie a ako sa odrážajú v našom vzťahu?",
    "Existuje niečo, čo sa učíš prijať sám/a na sebe v tomto období?",
    "Aké tvoje najväčšie ponaučenie z nášho spoločného života za posledný rok?",
    "Ktorá kniha alebo myšlienka ti v poslednom čase zmenila pohľad na svet?",
    "Akú vlastnosť alebo zručnosť by si si chcel/a v najbližších mesiacoch osvojiť?",
    "V čom cítiš, že sme sa ako pár za poslednú dobu najviac posunuli?",
    "Aké správanie druhých ľudí ťa vie najrýchlejšie vyviesť z miery a čo to hovorí o tebe?",
    "Na čo si vo svojom živote doteraz najviac hrdý/á?",
    "Čo pre teba znamená byť naozaj slobodný/á?",
    "Existuje nejaký strach, ktorého by si sa chcel/a zbaviť?",
    "Ako vnímaš starnutie a čoho sa na ňom (ne)obávaš?",
    "V čom sa tvoj pohľad na náš vzťah najviac zmenil od chvíle, keď sme spolu začali chodiť?",
    "Aké najťažšie rozhodnutie si musel/a v živote urobiť a ako ťa to ovplyvnilo?",
    "Existuje nejaká vec, ktorou by si chcel/a vo svojom živote začať brať viac vážne?",
    "Čo pre teba znamená pojem 'emocionálna zrelosť' a kedy máš pocit, že ju najviac prejavujeme?",
    "V akej oblasti nášho života by sme mali podľa teba viac komunikovať alebo byť otvorenejší?",
    "Aká je najlepšia rada o vzťahoch, akú si kedy počul/a alebo dostal/a?",
    "Čo ťa v našom vzťahu najviac učí trpezlivosti a ako sa s tým vyrovnávaš?",
    "Aký osobný úspech mimo práce za posledný rok ťa najviac potešil?",
    "Existuje niečo, čo na mne obdivuješ, no málokedy mi to hovoríš nahlas?",
    "Como vnímaš našu schopnosť riešiť konflikty? V čom sme sa zlepšili a kde máme rezervy?",
    "Ktorá tvoja vlastnosť ti v minulosti spôsobila najviac problémov a ako na nej pracuješ?",
    "Čo je pre teba najväčším zdrojom vnútornej motivácie, keď prežívaš náročné obdobie?",
    "Ako sa zmenil tvoj vzťah k vlastnému telu a zdraviu za posledné roky?",
    "Čo pre teba znamená 'podpora partnera' a kedy si ju odo mňa najsilnejšie cítil/a?",
    "Existuje nejaká chyba z minulosti, ktorú si ešte stále úplne neodpustil/a sám/a sebe?",
    "V akej chvíli nášho spoločného života si mal/a pocit, že sme naozaj silný a zohraný tím?",
    "Ktorá životná etapa bola pre teba doteraz najnáročnejšia a čo ťa naučila o tebe samotnom/samej?",
    "Aké správanie vo vzťahu považuješ za absolútne neakceptovateľné a prečo?",
    "V čom cítiš, že ti dávam najväčší priestor a slobodu byť sám/a sebou?",
    "Čo ťa v poslednom čase najviac prinútilo zamyslieť sa nad tvojimi životnými prioritami?",
    "Ako vyzerá tvoja predstava ideálneho prepojenia medzi prácou a osobným životom?",
    "Ktorá tvoja reakcia počas nášho posledného nedorozumenia ťa mrzí a ako by si ju chcel/a nabudúce zmeniť?",
    "Čo ťa najviac napĺňa pocitom vďačnosti, keď sa večer obzrieš za celým dňom?",
    "Ako by si definoval/a slovo 'dôvera' a čo ju v našom vzťahu najviac upevňuje?",
    "V čom si myslíš, že sme najviac rozdielni, a ako tieto rozdiely obohacujú náš vzťah?",
    "Čo je tvoja najväčšia túžba v oblasti tvojho osobného alebo duchovného rastu v tomto roku?",
    "Akú zmenu vo mojom správaní za posledné obdobie si postrehol/postrehla a ako ju vnímaš?",
    "Ako najradšej dobíjaš svoju psychickú energiu, keď sa cítiš úplne vyčerpaný/á?",
    "Ktorá oblasť nášho spoločného rozpočtu alebo narábania s peniazmi by si zaslúžila viac diskusie?",
    "Čo je podľa teba najkrajšia odmena za to, že spoločne prekonávame ťažké chvíle?"
  ],
  intimita: [
    "Kedy sa v mojej prítomnosti cítiš najviac milovaný/á a prijatý/á?",
    "Aké moje gesto, dotyk alebo slovo v tebe najrýchlejšie vyvolá pocit bezpečia a pokoja?",
    "Čo je pre teba najintímnejší moment, ktorý sme spolu doteraz zažili?",
    "Existuje niečo, čo by si chcel/a vyskúšať v našej fyzickej intimite, ale doteraz si to nepovedal/a?",
    "Čo je tvoj najobľúbenejší jazyk lásky a ako najradšej vyjadruješ lásku ty mne?",
    "Ktorá moja časť tela ťa najviac priťahuje a prečo?",
    "Como sa zmenilo tvoje vnímanie fyzickej blízkosti od začiatku nášho vzťahu?",
    "Čo pre teba znamená slovo 'zraniteľnosť' a kedy je pre teba ťažké ju predo mnou ukázať?",
    "Kedy na mňa najviac myslíš, keď sme od seba ďaleko?",
    "Aké sú tvoje najčastejšie romantické alebo erotické fantázie v poslednom čase?",
    "Čo môžem urobiť pre to, aby si sa v našom milostnom živote cítil/a ešte bezpečnejšie a uvoľnenejšie?",
    "Ktorý spoločný moment fyzického kontaktu (mimo sexu) ti prikniesol najviac radosti?",
    "Ako sa cítiš, keď sa na teba dlho dívam bez slov?",
    "Existuje nejaké zranenie z minulosti, o ktorom vieš, že ovplyvňuje to, ako dnes prežívaš našu blízkosť?",
    "Aké slovo alebo kompliment, ktorý som ti kedy povedal/a, ti najviac uviazol v pamäti?",
    "Čo ťa na mne dokáže stále najviac očariť alebo pritiahnuť?",
    "Ako vnímaš rovnováhu medzi našou fyzickou a emocionálnou intimitou?",
    "V akej chvíli dňa cítiš najsilnejšie prepojenie medzi nami?",
    "Čo ťa dokáže najspoľahlivejšie naladiť na romantickú vlnu?",
    "Čo je pre teba najkrajšia forma vyjadrenia dôvery?",
    "Ktorá časť nášho každodenného rituálu (túlenie pri káve, bozk na privítanie) je pre teba najdôležitejšia?",
    "Aké slovo alebo prezývku odo mňa najradšej počúvaš a vyvoláva v tebe hrejivý pocit?",
    "Existuje nejaký moment, kedy si sa pri mne cítil/a neuveriteľne bezpečne a chránene?",
    "Ako sa zmenil tvoj pohľad na moju príťažlivosť od chvíle, keď sme sa prvýkrát spoznali?",
    "Čo pre teba znamená 'emocionálne prepojenie' pred tým, ako sa začneme milovať?",
    "Aký kompliment o tvojej osobnosti alebo povahe ťa odo mňa najviac zahrial pri srdci?",
    "Ktoré naše spoločné ráno bolo pre teba najkrajšie a prečo?",
    "Ak by sme si mali dať 10-sekundový hlboký objatie zakaždým, keď prídeme domov, ako by to zmenilo náš deň?",
    "Existuje nejaká obava alebo citlivá téma, ktorú si sa mi doteraz bál/a zveriť, no chcel/a by si ju zdieľať?",
    "Čo ťa na mne najviac fascinuje, keď ma pozoruješ, keď o tom neviem?",
    "Aká forma nečakaného prejavu pozornosti (kvetina, odkaz v taške) ťa najviac poteší?",
    "Ako môžem lepšie oceniť tvoju zraniteľnosť, keď mi dôveruješ so svojimi pocitmi?",
    "Ktorá spomienka na náš spoločný intímny moment ťa sprevádza, keď sme cez dvor od seba?",
    "Ako vyzerá tvoja predstava o dokonalej emocionálnej blízkosti medzi nami?",
    "Čo ťa na mojich dotykoch najviac upokojuje, keď si smutný/á alebo rozrušený/á?",
    "Ktoré spoločné ticho bolo pre teba najpríjemnejšie a kedy sa pri mne cítiš dobre aj bez slov?",
    "Keby sme mali jeden večer stráviť len masážou a rozhovorom, aký olej alebo vôňu by si vybral/a?",
    "Aké správanie z mojej strany v tebe najviac prebúdza pocit, že som tvoj bezpečný prístav?",
    "Ako vnímaš našu úprimnosť vo vzťahu? Existuje téma, o ktorej máš pocit, že obchádzame pravdu?",
    "Čo pre teba znamená naša vernosť a akú hodnotu jej pripisuješ v dnešnom svete?",
    "Ktorý spoločný moment, kedy sme sa spolu smiali až k slzám, ťa najviac priblížil ku mne?",
    "Čo ťa na mojom dotyku na verejnosti (držanie za ruku, ruka na ramene) najviac teší?",
    "Existuje nejaký moment z našich začiatkov, kedy si si prvýkrát uvedomil/a, že ťa naozaj milujem?",
    "Ako môžem dať najavo, že ťa počúvam celým srdcom, keď mi rozprávaš o svojich trápeniach?",
    "Ktorá časť nášho rozhovoru o budúcnosti v tebe vyvoláva najväčší pocit bezpečia?",
    "Čo ťa na mojom správaní najviac utvrdzuje v tom, že ťa považujem za najdôležitejšieho človeka vo svojom živote?",
    "Ak by sme si mali napísať zoznam piatich vecí, ktoré na druhom najviac milujeme, čo by bolo tvoje číslo jeden?",
    "Kedy máš pocit, že sme na seba dokonale napojení a rozumieme si aj bez jediného gesta?",
    "Ktorý náš spoločný večer doma, bez akýchkoľvek plánov, bol pre teba nezabudnuteľný?",
    "Čo pre teba znamená veta 'patríme k sebe'? Ako ju prežívaš v každodennom živote?"
  ],
  sny: [
    "Keby sme mali neobmedzené množstvo peňazí a času, kde a ako by sme prežili nasledujúci rok?",
    "Ako vyzerá tvoja predstava nášho spoločného života o 10 rokov?",
    "Máš nejaký tajný sen alebo túžbu, o ktorej sme sa ešte nikdy podrobne nerozprávali?",
    "Aké spoločné dobrodružstvo alebo cestu by si chcel/a v najbližších rokoch podniknúť?",
    "Ako si predstavuješ náš spoločný ideálny domov? Kde by sa nachádzal a ako by to tam vyzeralo?",
    "Čo by si si prial/a, aby sme ako pár dokázali spoločne vybudovať alebo vytvoriť?",
    "Aký odkaz alebo stopy by si chcel/a, aby sme tu po sebe zanechali?",
    "Keby sme si mohli kúpiť spoločne nejakú chatku na samote, ako by sme tam trávili čas?",
    "Aký bláznivý alebo netradičný nápad by si chcel/a so mnou zrealizovať?",
    "Čo je tvoj najväčší sen pre mňa ako jednotlivca a ako ťa v ňom môžem podporiť?",
    "Ako vyzerá tvoja predstava nášho ideálneho spoločného víkendu o 20 rokov?",
    "Aké tradície alebo rituály by si chcel/a, aby sme vo našom vzťahu zaviedli alebo zachovali?",
    "Keby sme mali spoločne napísať knihu, o čom by bola?",
    "V akej krajine alebo meste by si si chcel/a vyskúšať bývať na pol roka?",
    "Čo je tvoj najväčší osobný profesijný alebo kreatívny sen, ktorý chceš ešte dosiahnuť?",
    "Aké spoločné hobby alebo aktivitu by si chcel/a, aby sme začali robiť?",
    "Čo by bolo na zozname tvojich 'top 5 vecí, ktoré chcem zažiť pred smrťou'?",
    "Ako vyzerá tvoj ideálny dôchodok s nami dvoma?",
    "Ak by sme mohli zmeniť jednu vec na našom životnom štýle hneď teraz, čo by to bolo?",
    "Čo ťa najviac napĺňa optimizmom, keď myslíš na našu spoločnú budúcnosť?",
    "Keby sme si mali kúpiť karavan a cestovať po Európe pol roka, akú trasu by si chcel/a zvoliť?",
    "Aké je tvoje najväčšie spoločné želanie pre našu rodinu na najbližšie tri roky?",
    "Ak by sme mali možnosť postaviť si ekologický domček v lese, chcel/a by si to vyskúšať?",
    "Existuje nejaká krajina, ktorú by si chcel/a navštíviť len preto, aby sme tam spoločne videli polárnu žiaru?",
    "Čo by si chcel/a, aby sme spoločne dosiahli v oblasti našich osobných kariér a ako sa môžeme navzájom podporovať?",
    "Ak by sme mali napísať zoznam piatich miest, ktoré musíme spoločne navštíviť predtým, než zostarneme, ktoré by to boli?",
    "Máš nejaký bláznivý sen o tom, že by sme spoločne skočili s padákom alebo vyskúšali nejaký adrenalínový šport?",
    "Ak by sme mali možnosť adoptovať si zvieratko z útulku, aké by to bolo a ako by sme sa oň starali?",
    "Aká je tvoja predstava o našich spoločných vianociach o 15 rokov? Kde a s kým by sme ich trávili?",
    "Čo je tvoj najväčší tajný sen týkajúci sa nášho bývania a dizajnu interiéru?",
    "Ak by sme mali vytvoriť spoločný charitatívny projekt alebo niekomu pomôcť, aká oblasť by to bola?",
    "Keby sme si mohli vybrať akékoľvek miesto na svete a prežiť tam jedno leto, kde by to bolo?",
    "Aký spoločný projekt (napr. prerábka záhrady, maľovanie izby) by si chcel/a začať v najbližších mesiacoch?",
    "Ako si predstavuješ naše oslavy narodenín o 10 rokov? Čo by si si prial/a zažiť?",
    "Existuje nejaké umelecké hobby (keramika, maľovanie, stolárstvo), ktoré by si chcel/a so mnou začať navštevovať?",
    "Čo by pre teba znamenalo, keby sme si spoločne kúpili malú vinicu alebo ovocný sad?",
    "Ak by sme mali možnosť prežiť rok na plachetnici, išiel/išla by si do toho so mnou?",
    "Aké vzdelanie alebo kurz (jazykový, kuchársky, odborný) by si si chcel/a v budúcnosti spoločne urobiť?",
    "Čo ťa najviac napĺňa radosťou, keď si predstavíš, že budeme spoločne vychovávať deti (alebo sa starať o našich budúcich vnukov)?",
    "Ktorý náš spoločný materiálny sen by si chcel/a splniť ako prvý a prečo?",
    "Aká je tvoja predstava o ideálnom cestovaní na dôchodku? Chcel/a by si viac spoznávať svet, alebo oddychovať v prírode?",
    "Ak by sme mali možnosť otvoriť si malú kaviareň alebo penzión, aký štýl a atmosféru by si tomu chcel/a dať?",
    "Keby sme mali napísať zoznam vecí, ktoré chceme spoločne zažiť za najbližší rok, čo by tam nesmelo chýbať?",
    "Aká je tvoja najväčšia osobná túžba, ktorú by si chcel/a dosiahnuť s mojou podporou?",
    "Ako vyzerá tvoja predstava o našom zdravom životnom štýle v budúcnosti? Čo by sme mali zmeniť?",
    "Čo by pre teba znamenalo, keby sme si spoločne kúpili starú chalupu a postupne ju svojpomocne prerábali?",
    "Aký druh spomienok chceš, aby sme si odniesli z každej našej spoločnej dovolenky?",
    "Keby sme mali možnosť urobiť si polročný sabatikal (voľno z práce) a venovať sa len sebe, ako by sme ten čas strávili?",
    "Aká je tvoja predstava o tom, ako budeme oslavovať naše 25. výročie vzťahu/manželstva?",
    "Čo je podľa teba ten najdôležitejšie spoločný cieľ, na ktorom by sme mali každý deň spoločne pracovať?"
  ],
  nocna: [
    "Ktorá časť tvojho tela je najcitlivejšia na môj dotyk a chcel/a by si, aby som sa jej venoval/a viac?",
    "Čo ťa na mne v posteli dokáže najrýchlejšie a najspoľahlivejšie vzrušiť?",
    "Máš nejakú erotickú fantáziu, o ktorej sme sa ešte nikdy nerozprávali, ale chcel/a by si ju vyskúšať?",
    "Ktorý náš spoločný intímny moment alebo milovanie považuješ za najvášnivejšie?",
    "Čo môžem urobiť pre to, aby si sa počas našich intímnych chvíľ cítil/a úplne uvoľnene a slobodne?",
    "Aká vôňa, osvetlenie alebo hudba v tebe najspoľahlivejšie prebúdza chuť na milovanie?",
    "Čo je podľa teba najdôležitejšie na to, aby sme si udržali vášeň a sexuálnu iskru aj po rokoch?",
    "Ktorý druh dotyku alebo pohladenia ti najviac chýba, keď sme od seba dlhšie preč?",
    "Existuje nejaké neobvyklé miesto (mimo spálne), kde by si chcel/a zažiť spontánnu blízkosť?",
    "Ako vyzerá tvoja predstava dokonalej, vášnivej noci pre nás dvoch?",
    "Aký typ spodnej bielizne, oblečenia alebo vzhľadu na mne považuješ za najviac sexy?",
    "Kedy si si naposledy uvedomil/a, že ma divoko túžiš pobozkať a dotknúť sa ma?",
    "Čo sa ti na našom milostnom živote najviac páči a v akej oblasti by si chcel/a viac experimentovať?",
    "Čo pre teba znamená spojenie medzi citovou blízkosťou a telesnou intimitou? Sú pre teba prepojené?",
    "Existuje nejaké zranenie z minulosti alebo obava, ktorá ti bráni plne sa uvoľniť v našej intimite?",
    "Aká bola tvoja prvá reakcia alebo myšlienka, keď sme spolu prvýkrát spali?",
    "Čo pre teba znamená pojem „vášeň“ v našom dlhodobom vzťahu?",
    "Ak by sme mali dnes večer vytvoriť novú intímnu tradíciu, čo by to bolo?",
    "Ktorú časť môjho tela najradšej bozkávaš a prečo?",
    "Ako môžem dať najavo, že po tebe túžim, bez toho, aby som musel/a čokoľvek povedať?",
    "Čo ťa na mne najviac priťahuje, keď sme v spoločnosti iných ľudí?",
    "Existuje nejaká hra alebo aktivita pre dospelých, ktorú by si si so mnou chcel/a zahrať?",
    "Aký je tvoj najobľúbenejší spôsob, ako ma priviesť k vzrušeniu?",
    "Ako by si opísal/a náš intímny život tromi slovami?",
    "Čo je pre teba dôležitejšie: pomalé a nežné milovanie, alebo divoká a nečakaná vášeň?",
    "Akú emóciu v tebe najviac vyvoláva naša fyzická blízkosť?",
    "Čo je najbláznivejšia vec, ktorú by si chcel/a zažiť v spálni (alebo mimo nej)?",
    "Aká doterajšia intímna spomienka na nás dvoch ti vie počas dňa najrýchlejšie vyčariť úsmev na tvári?",
    "Ak by sme mali na jeden večer hrať role dvoch cudzincov, aké by boli naše postavy?",
    "Ako vnímaš moju iniciatívu v intímnom živote? Chcel/a by si, aby som preberal/a iniciatívu častejšie?",
    "Čo ťa na mne najviac priťahovalo na začiatku nášho vzťahu a čo ťa najviac priťahuje dnes?",
    "Existuje nejaké pieseň alebo hudobný album, ktorý v tebe prebúdza romantickú alebo vášnivú náladu?",
    "Kedy sa cítiš najviac sexy a príťažlivo? Čo k tomu prispieva?",
    "Aká je tvoja najobľúbenejšia poloha pri milovaní a prečo?",
    "Ako najradšej odpočívaš bezprostredne po milovaní? (napr. túlenie, rozhovor, ticho)",
    "Čo je pre teba najlepší spôsob, ako sa znova prepojiť po období, keď sme boli veľmi zaneprázdnení?",
    "Keby si mal/a opísať moju zmyselnosť jedným slovom, aké by to bolo?",
    "Aký druh bozku máš najradšej? (napr. jemný na pery, vášnivý, bozky na krk)",
    "Máš radšej milovanie ráno, cez deň, alebo neskoro v noci?",
    "Čo môžem urobiť, aby si sa po náročnom dni cítil/a rozmaznávaný/á a fyzicky milovaný/á?",
    "Ktorá tvoja intímna túžba sa v našom vzťahu už splnila a veľmi ťa to potešilo?",
    "Ako vnímaš našu nahotu? Cítiš sa predo mnou úplne pohodlne a bezpečne bez oblečenia?",
    "Ktoré miesto na mojom tele ťa najviac fascinuje a prečo?",
    "Akú najzmyselnejšiu správu by si odo mňa chcel/a dostať počas dňa, keď sme v práci?",
    "Ktoré gesto alebo dotyk ti dáva najavo, že po tebe túžim ako po partnerovi/partnerke, nie len ako po kamarátovi?",
    "Ak by sme si mali naplánovať víkend plný len zmyselnosti a oddychu, ako by vyzeral?",
    "Čo ťa dokáže najrýchlejšie odpútať od milovania? (napr. myšlienky na prácu, hluk, nepohodlie)",
    "Aký kompliment ohľadom tvojho tela alebo intímneho vyžarovania ťa odo mňa najviac poteší?",
    "Keby sme mali natočiť náš vlastný, súkromný romantický film, aká scéna by v neme smela chýbať?",
    "Existuje nejaká intímna téma, o ktorej sa ti so mnou rozpráva ťažko, ale chcel/a by si ju prekonať?"
  ]
};

// Export pre použitie v prehliadači (ES Modules alebo globálna premenná)
if (typeof module !== "undefined" && module.exports) {
  module.exports = QUESTIONS;
} else {
  window.QUESTIONS = QUESTIONS;
}
